name = "wallet-connector"
main = "src/index.js"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2026-01-01"

[env.production]
name = "wallet-connect-prod"
routes = [
  { pattern = "resolutioncustodialdapp.pages.dev/api/*", zone_name = "resolutioncustodialdapp.pages.dev" }
]

[build]
command = "npm install"
cwd = "./"

[assets]
directory = "public"
